### ISSUE TITLE
Refactor certain components

### ISSUE THREAD

**Issue by Und3rf10w** [Und3rf10w/external_c2_framework#15]
In order to better facilitate the builder, there's a few changes that need to be made:

- Currently, the client does not respect the configured `block=` option, and has a hard coded value to wait between processing batches of jobs. In order to support multiple clients, this value needs to be configurable. Both the client and server have a `sleep()` timer configured. Base client code should be modified to read in a certain config value for this instead, [akin to how the server has it configured](https://github.com/Und3rf10w/external_c2_framework/blob/4fc3399adc818dc9bee23eb639d8158742ed4a43/builds/server/server.py#L94). In addition, a determination needs to be made where to have this timer set in within the batch of jobs. There's a few options for this: after all jobs (i.e. bottom of `interact()`, as in the server), before all jobs (i.e. top of `interact()`), or before calling `sendData()`. Best option is probably at the bottom of `interact()`, but that's subject to change during testing.

- All current client distributions have a hardcoded pipe value within the source code of the DLL. A mechanism needs to be made to replace this string in the source code before it is compiled. There's a really sleek implementation of this in [VBad](https://github.com/Pepitoh/VBad) that I'll most likely reimplement for this. This will also enable us to support basic obfuscation of the client when it is built down the road.

- A skeleton needs to be made for client that just holds the core functionality that could easily be edited to add the desired transport or encoding mechanism.

- Currently, the client and server handle the way they deal with data slightly differently. While this is already well documented, this has already caused some issues. In hindsight, the decision to have the server expect encoded data for `sendData()` and `retrieveData()`, while the client expects to have raw data sent to it's `sendData()` and `recvData()` was a poor one. A determination needs to be made to stick to one method that works for both. This will also eliminate the need to call `recvData()` and `retrieveData()` different names, and make construction of the builder process much more straight forward.

- As documented originally in #12 ([here](https://github.com/Und3rf10w/external_c2_framework/pull/12#issuecomment-361407454)), commonUtils needs to be refactored in cases where the transport needs to handle the data encoding instead of the server. Either a new function can be made, or a configuration option can be made in the transport that can be read in to determine how this should be handled. In the meantime, a workaround is documented in #13.

- Should probably look into redoing how client log messages are generated. This would be significantly easier if there was a fully python implementation of the client.

Once changes are made, we can more easily facilitate multi-threading and the builder. Eventually, I'll probably have to move to a more object-oriented design for all the components.

# Tasks

- [X] A skeleton needs to be made to for the client. - eeb981b 
- [X] The client should accept a configurable parameter for the block time
- [x] Standardize on where the block timer should be within the batch of jobs.
- [X] Construct a mechanism that can insert and/or replace certain configurable values (such as the `pipename`) in the client skeleton and associated dll source code. - 3905e39, 59cba27
- [ ] R̶e̶d̶e̶s̶i̶g̶n̶ ̶t̶h̶e̶ ̶i̶m̶p̶l̶e̶m̶e̶n̶t̶a̶t̶i̶o̶n̶ ̶o̶f̶ ̶`s̶e̶n̶d̶D̶a̶t̶a̶(̶)̶`,̶ ̶`r̶e̶c̶v̶D̶a̶t̶a̶(̶)̶`,̶ ̶a̶n̶d̶ ̶`r̶e̶t̶r̶i̶e̶v̶e̶D̶a̶t̶a̶(̶)̶` ̶t̶o̶ ̶b̶e̶t̶t̶e̶r̶ ̶h̶a̶n̶d̶l̶e̶ ̶c̶a̶s̶e̶s̶ ̶w̶h̶e̶r̶e̶ ̶d̶a̶t̶a̶ ̶h̶a̶s̶ ̶t̶o̶ ̶b̶e̶ ̶e̶n̶c̶o̶d̶e̶d̶ ̶o̶r̶ ̶d̶e̶c̶o̶d̶e̶d̶ ̶i̶n̶ ̶b̶a̶t̶c̶h̶e̶s̶,̶ ̶r̶a̶t̶h̶e̶r̶ ̶t̶h̶a̶n̶ ̶a̶l̶l̶ ̶a̶t̶ ̶o̶n̶c̶e̶.̶. - ed6b0d3 --- **tracked by #13**
- [X] A̶c̶c̶e̶p̶t̶ ̶r̶a̶w̶ ̶s̶t̶r̶i̶n̶g̶ ̶l̶i̶t̶e̶r̶a̶l̶s̶ ̶f̶o̶r̶ ̶c̶e̶r̶t̶a̶i̶n̶ ̶c̶o̶n̶f̶i̶g̶u̶r̶a̶t̶i̶o̶n̶ ̶o̶p̶t̶i̶o̶n̶s̶,̶ ̶s̶u̶c̶h̶ ̶a̶s̶ ̶p̶i̶p̶e̶n̶a̶m̶e̶    - 59cba27

**Comment by Und3rf10w** [comment]
With regards to the `block=` option, perhaps this should be implemented as a global, so that it is available to `transports` as well? An example of where this could be extremely useful can be [seen within the Imgurc2 implementation](https://github.com/Und3rf10w/external_c2_framework/blob/2ba1ef4fcbf7d1712eb9c9b18d6752fe50263885/builds/server/utils/transports/transport_imgur.py#L60). `getTokens()` is called from within the client's `prepTransport()`, which happens before the start of the batch of jobs. In this case `getTokens()` has logic that is essentially using the transport mechanism to poll for additional required information before it can actually receive the stager. If this is not yet available, it waits before trying to use the channel again. It'd be nice if that time could be the value stored in the `block` option, which would be extremely useful for channels that have apis that rely on rate limits or credits.

**Comment by Und3rf10w** [comment]
Commit eeb981b adds skeletons of the core client functionality that will eventually be utilized by the builder.

**Comment by Und3rf10w** [comment]
Commit 3905e39 adds a Variable Replacer `builderutils.VarReplacer` that will replace a given marker it identifies in a given file.

The marker is: ` ```[var:::$identifier_for_the_marker]``` `

**Comment by Und3rf10w** [comment]
Commit 59cba27 include massive restructure of the project, but will enable it to more rapidly evolve to meet goals on the roadmap.

### Overview of changes
- Additional functionality was added to `builderutils.VarReplacer`

- `builderutils.VarReplacer` was renamed to `builderutils.SkeletonHandler` to better signify its purpose.

- The `builds` directory was moved to `sample_builds`. The `builds` directory will be the target directory for the builder's output.

- A `skeletons` directory was created, and the skeletons originally in `clientcore` was moved there.

- A `modules` directory was created, and existing modules were copied into it.

**Comment by Und3rf10w** [comment]
Commit ed6b0d3 sees yet another reorg to help better facilitate fixing #16

**Comment by Und3rf10w** [comment]
Updated tasks, eliminated one since it's being tracked in other areas. Would like to close this issue to reduce clutter, especially since there's no need to the same bug across multiple issues.
